### ISSUE TITLE
OpenShift tests failing

### ISSUE THREAD

**Issue by cdrage** [kedgeproject/kedge#568]
Just troubleshooting now, seems like they're simply timing out:

```sh
TEST=os make test-e2e 
make[1]: Entering directory `/home/runner/kedge'
./scripts/run_e2e.sh
======================================
| Running end-to-end cluster tests.  |
| Tests will be ran against a k8s    |
| cluster in separate namespaces     |
|                                    |
| Use command:                       |
| VERBOSE=yes make test-e2e-os       |
| for verbosity.                     |
======================================

NAMESPACE   NAME                            READY     STATUS              RESTARTS   AGE
default     docker-registry-1-96392         0/1       ContainerCreating   0          13s
default     docker-registry-1-deploy        1/1       Running             0          28s
default     persistent-volume-setup-vmpk3   1/1       Running             0          28s
default     router-1-72nvw                  0/1       ContainerCreating   0          10s
default     router-1-deploy                 1/1       Running             0          26s
=== RUN   Test_os_Integration
=== RUN   Test_os_Integration/Testing_routes
=== RUN   Test_os_Integration/Testing_buildconfig
=== RUN   Test_os_Integration/Testing_s2i_image
testroutes   httpd-2896424104-qtzq3   0/1       Pending   0         0s
testroutes   httpd-2896424104-qtzq3   0/1       Pending   0         1s
testroutes   httpd-2896424104-qtzq3   0/1       ContainerCreating   0         1s
s2i       s2i-1-build   0/1       Pending   0         0s
s2i       s2i-1-build   0/1       Pending   0         0s
buildconfig   ruby-1-build   0/1       Pending   0         0s
buildconfig   ruby-1-build   0/1       Pending   0         1s
s2i       s2i-1-build   0/1       ContainerCreating   0         1s
buildconfig   ruby-1-build   0/1       ContainerCreating   0         2s
default   docker-registry-1-96392   0/1       Running   0         1m
default   docker-registry-1-96392   1/1       Running   0         1m
default   docker-registry-1-deploy   0/1       Completed   0         2m
default   docker-registry-1-deploy   0/1       Terminating   0         2m
default   docker-registry-1-deploy   0/1       Terminating   0         2m
default   router-1-72nvw   0/1       Running   0         1m
default   router-1-72nvw   1/1       Running   0         2m
default   router-1-deploy   0/1       Completed   0         2m
default   router-1-deploy   0/1       Terminating   0         2m
default   router-1-deploy   0/1       Terminating   0         2m
testroutes   httpd-2896424104-qtzq3   1/1       Running   0         1m
s2i       s2i-1-build   1/1       Running   0         1m
buildconfig   ruby-1-build   1/1       Running   0         1m
default   persistent-volume-setup-vmpk3   0/1       Completed   0         3m
s2i       s2i-1-build   0/1       Completed   0         8m
buildconfig   ruby-1-deploy   0/1       Pending   0         0s
buildconfig   ruby-1-deploy   0/1       Pending   0         1s
buildconfig   ruby-1-deploy   0/1       ContainerCreating   0         1s
buildconfig   ruby-1-build   0/1       Completed   0         8m
s2i       redis-1-deploy   0/1       Pending   0         0s
s2i       redis-1-deploy   0/1       Pending   0         0s
s2i       redis-1-deploy   0/1       ContainerCreating   0         0s
s2i       redis-1-deploy   1/1       Running   0         3s
buildconfig   ruby-1-deploy   1/1       Running   0         5s
s2i       redis-1-z8963   0/1       Pending   0         0s
s2i       redis-1-z8963   0/1       Pending   0         0s
s2i       redis-1-z8963   0/1       ContainerCreating   0         0s
buildconfig   ruby-1-build   0/1       Terminating   0         8m
buildconfig   ruby-1-build   0/1       Terminating   0         8m
buildconfig   ruby-1-deploy   1/1       Terminating   0         8s
buildconfig   ruby-1-deploy   0/1       Terminating   0         10s
buildconfig   ruby-1-deploy   0/1       Terminating   0         11s
buildconfig   ruby-1-deploy   0/1       Terminating   0         11s
s2i       redis-1-deploy   1/1       Terminating   0         11s
s2i       redis-1-z8963   0/1       Terminating   0         8s
s2i       s2i-1-build   0/1       Terminating   0         8m
s2i       s2i-1-build   0/1       Terminating   0         8m
s2i       redis-1-z8963   0/1       Terminating   0         8s
s2i       redis-1-z8963   0/1       Terminating   0         10s
s2i       redis-1-z8963   0/1       Terminating   0         10s
s2i       redis-1-deploy   0/1       Terminating   0         13s
s2i       redis-1-deploy   0/1       Terminating   0         22s
s2i       redis-1-deploy   0/1       Terminating   0         22s
SIGQUIT: quit
PC=0x45f321 m=0 sigcode=0

goroutine 0 [idle]:
runtime.futex(0x1a13570, 0x0, 0x0, 0x0, 0x0, 0xc400000000, 0x0, 0x0, 0x7fff26567218, 0x4112ab, ...)
	/usr/local/golang/1.9.2/go/src/runtime/sys_linux_amd64.s:438 +0x21
runtime.futexsleep(0x1a13570, 0x100000000, 0xffffffffffffffff)
	/usr/local/golang/1.9.2/go/src/runtime/os_linux.go:45 +0x62
runtime.notesleep(0x1a13570)
	/usr/local/golang/1.9.2/go/src/runtime/lock_futex.go:151 +0x9b
runtime.stopm()
	/usr/local/golang/1.9.2/go/src/runtime/proc.go:1680 +0xe5
runtime.findrunnable(0xc420024000, 0x0)
	/usr/local/golang/1.9.2/go/src/runtime/proc.go:2135 +0x4d2
runtime.schedule()
	/usr/local/golang/1.9.2/go/src/runtime/proc.go:2255 +0x12c
runtime.park_m(0xc42066ac00)
	/usr/local/golang/1.9.2/go/src/runtime/proc.go:2318 +0xb6
runtime.mcall(0x7fff265673b0)
	/usr/local/golang/1.9.2/go/src/runtime/asm_amd64.s:286 +0x5b

goroutine 1 [chan receive, 9 minutes]:
testing.(*T).Run(0xc42048f680, 0x11ff773, 0x13, 0x1262928, 0x481901)
	/usr/local/golang/1.9.2/go/src/testing/testing.go:790 +0x2fc
testing.runTests.func1(0xc42048f680)
	/usr/local/golang/1.9.2/go/src/testing/testing.go:1004 +0x64
testing.tRunner(0xc42048f680, 0xc4205adde0)
	/usr/local/golang/1.9.2/go/src/testing/testing.go:746 +0xd0
testing.runTests(0xc420426de0, 0x1a06880, 0x3, 0x3, 0x2f)
	/usr/local/golang/1.9.2/go/src/testing/testing.go:1002 +0x2d8
testing.(*M).Run(0xc42072df18, 0xc4205adf70)
	/usr/local/golang/1.9.2/go/src/testing/testing.go:921 +0x111
main.main()
	github.com/kedgeproject/kedge/tests/e2e/_test/_testmain.go:48 +0xdb

goroutine 9 [chan receive]:
github.com/kedgeproject/kedge/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x1a12a00)
	/home/runner/workspace/src/github.com/kedgeproject/kedge/vendor/github.com/golang/glog/glog.go:879 +0x9f
created by github.com/kedgeproject/kedge/vendor/github.com/golang/glog.init.0
	/home/runner/workspace/src/github.com/kedgeproject/kedge/vendor/github.com/golang/glog/glog.go:410 +0x203

goroutine 19 [chan receive, 9 minutes]:
testing.tRunner.func1(0xc42048f770)
	/usr/local/golang/1.9.2/go/src/testing/testing.go:722 +0x131
testing.tRunner(0xc42048f770, 0x1262928)
	/usr/local/golang/1.9.2/go/src/testing/testing.go:748 +0xda
created by testing.(*T).Run
	/usr/local/golang/1.9.2/go/src/testing/testing.go:789 +0x2de

goroutine 36 [IO wait]:
internal/poll.runtime_pollWait(0x2b82b4987f70, 0x72, 0x0)
	/usr/local/golang/1.9.2/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc420105318, 0x72, 0xffffffffffffff00, 0x199b6e0, 0x19925c8)
	/usr/local/golang/1.9.2/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc420105318, 0xc4201fc000, 0x4000, 0x4000)
	/usr/local/golang/1.9.2/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc420105300, 0xc4201fc000, 0x4000, 0x4000, 0x0, 0x0, 0x0)
	/usr/local/golang/1.9.2/go/src/internal/poll/fd_unix.go:126 +0x18a
net.(*netFD).Read(0xc420105300, 0xc4201fc000, 0x4000, 0x4000, 0x28d, 0x8, 0x0)
	/usr/local/golang/1.9.2/go/src/net/fd_unix.go:202 +0x52
net.(*conn).Read(0xc42000e030, 0xc4201fc000, 0x4000, 0x4000, 0x0, 0x0, 0x0)
	/usr/local/golang/1.9.2/go/src/net/net.go:176 +0x6d
crypto/tls.(*block).readFromUntil(0xc4202cc120, 0x2b82b49d9620, 0xc42000e030, 0x5, 0xc42000e030, 0x0)
	/usr/local/golang/1.9.2/go/src/crypto/tls/conn.go:488 +0x95
crypto/tls.(*Conn).readRecord(0xc420125180, 0x1268717, 0xc4201252a0, 0x0)
	/usr/local/golang/1.9.2/go/src/crypto/tls/conn.go:590 +0xe0
crypto/tls.(*Conn).Read(0xc420125180, 0xc42055a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/golang/1.9.2/go/src/crypto/tls/conn.go:1134 +0x110
bufio.(*Reader).Read(0xc4204cc720, 0xc42013f218, 0x9, 0x9, 0x42c6d6, 0x1268700, 0x0)
	/usr/local/golang/1.9.2/go/src/bufio/bufio.go:213 +0x30b
io.ReadAtLeast(0x1993da0, 0xc4204cc720, 0xc42013f218, 0x9, 0x9, 0x9, 0xc42003fcd0, 0x406c22, 0xc4201f7f80)
	/usr/local/golang/1.9.2/go/src/io/io.go:309 +0x86
io.ReadFull(0x1993da0, 0xc4204cc720, 0xc42013f218, 0x9, 0x9, 0xc42003fd08, 0xc400000101, 0xc420045b30)
	/usr/local/golang/1.9.2/go/src/io/io.go:327 +0x58
github.com/kedgeproject/kedge/vendor/golang.org/x/net/http2.readFrameHeader(0xc42013f218, 0x9, 0x9, 0x1993da0, 0xc4204cc720, 0x0, 0xc400000000, 0x844c0f, 0xc42003ffb0)
	/home/runner/workspace/src/github.com/kedgeproject/kedge/vendor/golang.org/x/net/http2/frame.go:237 +0x7b
github.com/kedgeproject/kedge/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc42013f1e0, 0xc42019d0e0, 0x0, 0x0, 0x0)
	/home/runner/workspace/src/github.com/kedgeproject/kedge/vendor/golang.org/x/net/http2/frame.go:469 +0xa4
github.com/kedgeproject/kedge/vendor/golang.org/x/net/http2.(*clientConnReadLoop).run(0xc42003ffb0, 0x1264378, 0xc4204affb0)
	/home/runner/workspace/src/github.com/kedgeproject/kedge/vendor/golang.org/x/net/http2/transport.go:1343 +0x90
github.com/kedgeproject/kedge/vendor/golang.org/x/net/http2.(*ClientConn).readLoop(0xc4203f64e0)
	/home/runner/workspace/src/github.com/kedgeproject/kedge/vendor/golang.org/x/net/http2/transport.go:1269 +0x9d
created by github.com/kedgeproject/kedge/vendor/golang.org/x/net/http2.(*Transport).newClientConn
	/home/runner/workspace/src/github.com/kedgeproject/kedge/vendor/golang.org/x/net/http2/transport.go:534 +0x6b9

goroutine 20 [sleep]:
time.Sleep(0x3b9aca00)
	/usr/local/golang/1.9.2/go/src/runtime/time.go:65 +0x130
github.com/kedgeproject/kedge/tests/e2e.pingEndPoints(0xc4205a0000, 0xc4203437d0, 0x11f7f09, 0xa)
	/home/runner/workspace/src/github.com/kedgeproject/kedge/tests/e2e/e2e.go:218 +0x2a7
github.com/kedgeproject/kedge/tests/e2e.Test_os_Integration.func1(0xc4205a0000)
	/home/runner/workspace/src/github.com/kedgeproject/kedge/tests/e2e/e2e_os_test.go:141 +0x93a
testing.tRunner(0xc4205a0000, 0xc42032b4c0)
	/usr/local/golang/1.9.2/go/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
	/usr/local/golang/1.9.2/go/src/testing/testing.go:789 +0x2de

goroutine 21 [chan send]:
testing.tRunner.func1(0xc4205a00f0)
	/usr/local/golang/1.9.2/go/src/testing/testing.go:741 +0x19b
testing.tRunner(0xc4205a00f0, 0xc42032b520)
	/usr/local/golang/1.9.2/go/src/testing/testing.go:748 +0xda
created by testing.(*T).Run
	/usr/local/golang/1.9.2/go/src/testing/testing.go:789 +0x2de

goroutine 22 [chan send]:
testing.tRunner.func1(0xc4205a01e0)
	/usr/local/golang/1.9.2/go/src/testing/testing.go:741 +0x19b
testing.tRunner(0xc4205a01e0, 0xc42032b560)
	/usr/local/golang/1.9.2/go/src/testing/testing.go:748 +0xda
created by testing.(*T).Run
	/usr/local/golang/1.9.2/go/src/testing/testing.go:789 +0x2de

rax    0xca
rbx    0x1a13460
rcx    0xffffffffffffffff
rdx    0x0
rdi    0x1a13570
rsi    0x0
rbp    0x7fff265671e0
rsp    0x7fff26567198
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0x1
r13    0xc420078d20
r14    0x1
r15    0x0
rip    0x45f321
rflags 0x286
cs     0x33
fs     0x0
gs     0x0
*** Test killed with quit: ran too long (10m0s).
FAIL	github.com/kedgeproject/kedge/tests/e2e	600.009s
make[1]: *** [test-e2e] Error 1
make[1]: Leaving directory `/home/runner/kedge'
make: *** [test-e2e-os] Error 2
```

**Comment by ashetty1** [comment]
Could have been a timeout issue?

**Comment by ashetty1** [comment]
There's a possibility of a minor problem with running the OpenShift tests parallelly. Since `kedge build` doesn't allow namespace to be specified, there's a chance that it ends up creating the s2i build in some other namespace.

**Comment by cdrage** [comment]
@ashetty1 I'll try that, thank you!

**Comment by surajnarwade** [comment]
Tests are passing locally
